import { BOTH_PEDALS, GP50_ONLY } from "@/device/catalog/shared";
import type { FxControl, FxModel, WireIdentity } from "@/device/catalog/types";

const CAB_VOL: FxControl = {
  index: 0,
  label: "VOL",
  min: 0,
  max: 100,
  step: 1,
  default: 50,
  display: "percent",
};

/** Twenty onboard cabinet IR slots. Byte 0 is the slot index; byte 2 is the user-IR marker. */
const USER_IR_CAB_MODELS: readonly FxModel[] = Array.from({ length: 20 }, (_, index) => {
  const slot = index + 1;
  const nn = String(slot).padStart(2, "0");
  const wire: WireIdentity = [index, 0x00, 0x10, 0x0a];
  return {
    id: `cab-user-ir-${nn}`,
    kind: "cab",
    label: `User IR ${nn}`,
    devices: BOTH_PEDALS,
    wire,
    userIrSlot: slot,
    controls: [CAB_VOL],
  };
});

export const CAB_MODELS: readonly FxModel[] = [
  {
    id: "cab-twd-cp-1x8",
    kind: "cab",
    label: "TWD CP 1x8",
    description: "Vintage Fender® Champ* 1x8\" cabinet.",
    basedOn: "Fender Champ 1x8\"",
    devices: BOTH_PEDALS,
    wire: [0x01, 0x00, 0x00, 0x0a],
    controls: [
      {
        index: 0,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "cab-dark-vit-1x12",
    kind: "cab",
    label: "Dark VIT 1x12",
    description: "Vintage Fender® Vibrolux* 1x12\" cabinet.",
    basedOn: "Fender Vibrolux 1x12\"",
    devices: BOTH_PEDALS,
    wire: [0x04, 0x00, 0x00, 0x0a],
    controls: [
      {
        index: 0,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "cab-foxy-1x12",
    kind: "cab",
    label: "Foxy 1x12",
    description: "Vintage VOX® AC15* 1x12\" cabinet.",
    basedOn: "VOX AC15 1x12\"",
    devices: BOTH_PEDALS,
    wire: [0x08, 0x00, 0x00, 0x0a],
    controls: [
      {
        index: 0,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "cab-l-star-1x12",
    kind: "cab",
    label: "L-Star 1x12",
    description: "Mesa/Boogie® Lonestar* 1x12\" cabinet.",
    basedOn: "Mesa/Boogie Lonestar 1x12\"",
    devices: BOTH_PEDALS,
    wire: [0x09, 0x00, 0x00, 0x0a],
    controls: [
      {
        index: 0,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "cab-dark-cs-2x12",
    kind: "cab",
    label: "Dark CS 2x12",
    description: "Custom modified Fender®* 2x12\" cabinet.",
    basedOn: "Fender 2x12\"",
    devices: BOTH_PEDALS,
    wire: [0x1b, 0x00, 0x00, 0x0a],
    controls: [
      {
        index: 0,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "cab-dark-twin-2x12",
    kind: "cab",
    label: "Dark Twin 2x12",
    description: "Vintage Fender® '65 Twin Reverb* 2x12\" cabinet.",
    basedOn: "Fender '65 Twin Reverb 2x12\"",
    devices: BOTH_PEDALS,
    wire: [0x12, 0x00, 0x00, 0x0a],
    controls: [
      {
        index: 0,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "cab-sup-star-2x12",
    kind: "cab",
    label: "SUP Star 2x12",
    description: "Mesa/Boogie® Lonestar* 2x12\" cabinet.",
    basedOn: "Mesa/Boogie Lonestar 2x12\"",
    devices: BOTH_PEDALS,
    wire: [0x19, 0x00, 0x00, 0x0a],
    controls: [
      {
        index: 0,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "cab-j-120-2x12",
    kind: "cab",
    label: "J-120 2x12",
    description: "Legendary \"Jazz Chorus\" 2x12\" cabinet.",
    basedOn: "\"Jazz Chorus\" 2x12\"",
    devices: BOTH_PEDALS,
    wire: [0x11, 0x00, 0x00, 0x0a],
    controls: [
      {
        index: 0,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "cab-foxy-2x12",
    kind: "cab",
    label: "Foxy 2x12",
    description: "Vintage VOX® AC30* 2x12\" cabinet.",
    basedOn: "VOX AC30 2x12\"",
    devices: BOTH_PEDALS,
    wire: [0x0f, 0x00, 0x00, 0x0a],
    controls: [
      {
        index: 0,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "cab-uk-grn-2x12",
    kind: "cab",
    label: "UK GRN 2x12",
    description: "Small Cab Marshall® 2550* 2x12\" cabinet.",
    basedOn: "Small Cab Marshall 2550 2x12\"",
    devices: BOTH_PEDALS,
    wire: [0x13, 0x00, 0x00, 0x0a],
    controls: [
      {
        index: 0,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "cab-uk-grn-4x12",
    kind: "cab",
    label: "UK GRN 4x12",
    description: "Vintage Marshall® 4x12\" cabinet with Celestion® Greenback®* speakers.",
    devices: BOTH_PEDALS,
    wire: [0x22, 0x00, 0x00, 0x0a],
    controls: [
      {
        index: 0,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "cab-bog-4x12",
    kind: "cab",
    label: "Bog 4x12",
    description: "Bogner®* 4x12\" cabinet.",
    basedOn: "Bogner 4x12\" cabinet.",
    devices: BOTH_PEDALS,
    wire: [0x25, 0x00, 0x00, 0x0a],
    controls: [
      {
        index: 0,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "cab-dizz-4x12",
    kind: "cab",
    label: "Dizz 4x12",
    description: "Diezel®* 4x12\" cabinet.",
    basedOn: "Diezel 4x12\" cabinet.",
    devices: BOTH_PEDALS,
    wire: [0x2e, 0x00, 0x00, 0x0a],
    controls: [
      {
        index: 0,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "cab-ev-4x12",
    kind: "cab",
    label: "EV 4x12",
    description: "Peavey® 6505* 4x12\" cabinet.",
    basedOn: "Peavey 6505 4x12\" cabinet.",
    devices: BOTH_PEDALS,
    wire: [0x20, 0x00, 0x00, 0x0a],
    controls: [
      {
        index: 0,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "cab-solo-4x12",
    kind: "cab",
    label: "Solo 4x12",
    description: "Soldano®* 4x12\" cabinet.",
    basedOn: "Soldano 4x12\"",
    devices: BOTH_PEDALS,
    wire: [0x28, 0x00, 0x00, 0x0a],
    controls: [
      {
        index: 0,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "cab-mess-4x12",
    kind: "cab",
    label: "Mess 4x12",
    description: "Mesa/Boogie® Rectifier®* 4x12\" cabinet.",
    basedOn: "Mesa/Boogie Rectifier 4x12\"",
    devices: BOTH_PEDALS,
    wire: [0x24, 0x00, 0x00, 0x0a],
    controls: [
      {
        index: 0,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "cab-eagle-4x12",
    kind: "cab",
    label: "Eagle 4x12",
    description: "ENGL®* 4x12\" cabinet.",
    basedOn: "ENGL 4x12\" cabinet.",
    devices: BOTH_PEDALS,
    wire: [0x26, 0x00, 0x00, 0x0a],
    controls: [
      {
        index: 0,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "cab-juice-4x12",
    kind: "cab",
    label: "Juice 4x12",
    description: "Orange® PPC412* 4x12\" cabinet.",
    basedOn: "Orange PPC412 4x12\"",
    devices: BOTH_PEDALS,
    wire: [0x29, 0x00, 0x00, 0x0a],
    controls: [
      {
        index: 0,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "cab-bellman-2x12",
    kind: "cab",
    label: "Bellman 2x12",
    description: "Vintgae Fender® \"Piggyback\" Bassman®* 2x12\" cabinet.",
    basedOn: "Fender \"Piggyback\" Bassman 2x12\"",
    devices: BOTH_PEDALS,
    wire: [0x16, 0x00, 0x00, 0x0a],
    controls: [
      {
        index: 0,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "cab-ampg-4x10",
    kind: "cab",
    label: "AMPG 4x10",
    description: "Ampeg® SVT-410HE* 4x10\" bass cabinet.",
    basedOn: "Ampeg SVT-410HE 4x10\" bass",
    devices: BOTH_PEDALS,
    wire: [0x38, 0x00, 0x00, 0x0a],
    controls: [
      {
        index: 0,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "cab-ac",
    kind: "cab",
    label: "AC",
    description: "",
    devices: GP50_ONLY,
    wire: [0x3c, 0x00, 0x00, 0x0a],
    controls: [
      {
        index: 0,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  ...USER_IR_CAB_MODELS,
];
