import { BOTH_PEDALS } from "@/device/catalog/shared";
import type { FxModel } from "@/device/catalog/types";

export const DLY_MODELS: readonly FxModel[] = [
  {
    id: "dly-pure",
    kind: "dly",
    label: "Pure",
    devices: BOTH_PEDALS,
    wire: [0x00, 0x00, 0x00, 0x0b],
    controls: [
      {
        index: 0,
        label: "Mix",
        min: 0,
        max: 100,
        step: 1,
        default: 20,
        display: "percent",
      },
      {
        index: 1,
        label: "Time",
        min: 20,
        max: 1000,
        step: 1,
        default: 500,
        display: "time",
      },
      {
        index: 2,
        label: "F.Back",
        min: 0,
        max: 100,
        step: 1,
        default: 30,
        display: "percent",
      },
      {
        index: 3,
        label: "Sync",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
      {
        index: 4,
        label: "Trail",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "dly-analog",
    kind: "dly",
    label: "Analog",
    devices: BOTH_PEDALS,
    wire: [0x01, 0x00, 0x00, 0x0b],
    controls: [
      {
        index: 0,
        label: "Mix",
        min: 0,
        max: 100,
        step: 1,
        default: 20,
        display: "percent",
      },
      {
        index: 1,
        label: "Time",
        min: 20,
        max: 1000,
        step: 1,
        default: 500,
        display: "time",
      },
      {
        index: 2,
        label: "F.Back",
        min: 0,
        max: 100,
        step: 1,
        default: 30,
        display: "percent",
      },
      {
        index: 3,
        label: "Sync",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
      {
        index: 4,
        label: "Trail",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "dly-slapback",
    kind: "dly",
    label: "Slapback",
    devices: BOTH_PEDALS,
    wire: [0x05, 0x00, 0x00, 0x0b],
    controls: [
      {
        index: 0,
        label: "Mix",
        min: 0,
        max: 100,
        step: 1,
        default: 20,
        display: "percent",
      },
      {
        index: 1,
        label: "Time",
        min: 20,
        max: 300,
        step: 1,
        default: 150,
        display: "time",
      },
      {
        index: 2,
        label: "F.Back",
        min: 0,
        max: 100,
        step: 1,
        default: 30,
        display: "percent",
      },
      {
        index: 4,
        label: "Trail",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "dly-sweet-echo",
    kind: "dly",
    label: "Sweet Echo",
    devices: BOTH_PEDALS,
    wire: [0x0d, 0x00, 0x00, 0x0b],
    controls: [
      {
        index: 0,
        label: "Mix",
        min: 0,
        max: 100,
        step: 1,
        default: 20,
        display: "percent",
      },
      {
        index: 1,
        label: "Time",
        min: 20,
        max: 1000,
        step: 1,
        default: 500,
        display: "time",
      },
      {
        index: 2,
        label: "F.Back",
        min: 0,
        max: 100,
        step: 1,
        default: 30,
        display: "percent",
      },
      {
        index: 3,
        label: "Sync",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
      {
        index: 4,
        label: "Trail",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "dly-tape",
    kind: "dly",
    label: "Tape",
    devices: BOTH_PEDALS,
    wire: [0x02, 0x00, 0x00, 0x0b],
    controls: [
      {
        index: 0,
        label: "Mix",
        min: 0,
        max: 100,
        step: 1,
        default: 20,
        display: "percent",
      },
      {
        index: 1,
        label: "Time",
        min: 20,
        max: 1000,
        step: 1,
        default: 500,
        display: "time",
      },
      {
        index: 2,
        label: "F.Back",
        min: 0,
        max: 100,
        step: 1,
        default: 30,
        display: "percent",
      },
      {
        index: 3,
        label: "Sync",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
      {
        index: 4,
        label: "Trail",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "dly-tube",
    kind: "dly",
    label: "Tube",
    devices: BOTH_PEDALS,
    wire: [0x0b, 0x00, 0x00, 0x0b],
    controls: [
      {
        index: 0,
        label: "Mix",
        min: 0,
        max: 100,
        step: 1,
        default: 20,
        display: "percent",
      },
      {
        index: 1,
        label: "Time",
        min: 20,
        max: 1000,
        step: 1,
        default: 500,
        display: "time",
      },
      {
        index: 2,
        label: "F.Back",
        min: 0,
        max: 100,
        step: 1,
        default: 30,
        display: "percent",
      },
      {
        index: 3,
        label: "Sync",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
      {
        index: 4,
        label: "Trail",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "dly-rev-echo",
    kind: "dly",
    label: "Rev Echo",
    devices: BOTH_PEDALS,
    wire: [0x13, 0x00, 0x00, 0x0b],
    controls: [
      {
        index: 0,
        label: "Mix",
        min: 0,
        max: 100,
        step: 1,
        default: 20,
        display: "percent",
      },
      {
        index: 1,
        label: "Time",
        min: 20,
        max: 1000,
        step: 1,
        default: 500,
        display: "time",
      },
      {
        index: 2,
        label: "F.Back",
        min: 0,
        max: 100,
        step: 1,
        default: 30,
        display: "percent",
      },
      {
        index: 3,
        label: "Sync",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
      {
        index: 4,
        label: "Trail",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "dly-ring-echo",
    kind: "dly",
    label: "Ring Echo",
    devices: BOTH_PEDALS,
    wire: [0x09, 0x00, 0x00, 0x0b],
    controls: [
      {
        index: 0,
        label: "Mix",
        min: 0,
        max: 100,
        step: 1,
        default: 20,
        display: "percent",
      },
      {
        index: 1,
        label: "Time",
        min: 20,
        max: 1000,
        step: 1,
        default: 500,
        display: "time",
      },
      {
        index: 2,
        label: "F.Back",
        min: 0,
        max: 100,
        step: 1,
        default: 30,
        display: "percent",
      },
      {
        index: 3,
        label: "R-Mix",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Freq",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 5,
        label: "Tone",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 6,
        label: "Sync",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
      {
        index: 7,
        label: "Trail",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "dly-sweep-echo",
    kind: "dly",
    label: "Sweep Echo",
    devices: BOTH_PEDALS,
    wire: [0x06, 0x00, 0x00, 0x0b],
    controls: [
      {
        index: 0,
        label: "Mix",
        min: 0,
        max: 100,
        step: 1,
        default: 20,
        display: "percent",
      },
      {
        index: 1,
        label: "Time",
        min: 20,
        max: 1000,
        step: 1,
        default: 500,
        display: "time",
      },
      {
        index: 2,
        label: "F.Back",
        min: 0,
        max: 100,
        step: 1,
        default: 30,
        display: "percent",
      },
      {
        index: 3,
        label: "S-Depth",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "S-Rate",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 5,
        label: "S-Sync",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
      {
        index: 6,
        label: "D-Sync",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
      {
        index: 7,
        label: "Trail",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "dly-ping-pong",
    kind: "dly",
    label: "Ping Pong",
    devices: BOTH_PEDALS,
    wire: [0x04, 0x00, 0x00, 0x0b],
    controls: [
      {
        index: 0,
        label: "Mix",
        min: 0,
        max: 100,
        step: 1,
        default: 20,
        display: "percent",
      },
      {
        index: 1,
        label: "Time",
        min: 20,
        max: 500,
        step: 1,
        default: 500,
        display: "time",
      },
      {
        index: 2,
        label: "F.Back",
        min: 0,
        max: 100,
        step: 1,
        default: 30,
        display: "percent",
      },
      {
        index: 3,
        label: "Sync",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
      {
        index: 4,
        label: "Trail",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
];
