import { BOTH_PEDALS } from "@/device/catalog/shared";
import type { FxModel } from "@/device/catalog/types";

export const DST_MODELS: readonly FxModel[] = [
  {
    id: "dst-green-od",
    kind: "dst",
    label: "Green OD",
    devices: BOTH_PEDALS,
    wire: [0x00, 0x00, 0x00, 0x03],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 40,
        display: "percent",
      },
      {
        index: 1,
        label: "Tone",
        min: 0,
        max: 100,
        step: 1,
        default: 70,
        display: "percent",
      },
      {
        index: 2,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "dst-yellow-od",
    kind: "dst",
    label: "Yellow OD",
    devices: BOTH_PEDALS,
    wire: [0x02, 0x00, 0x00, 0x03],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 40,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "dst-super-od",
    kind: "dst",
    label: "Super OD",
    devices: BOTH_PEDALS,
    wire: [0x06, 0x00, 0x00, 0x03],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Tone",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "dst-sm-dist",
    kind: "dst",
    label: "SM Dist",
    devices: BOTH_PEDALS,
    wire: [0x2a, 0x00, 0x00, 0x03],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Tone",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "dst-plustortion",
    kind: "dst",
    label: "Plustortion",
    devices: BOTH_PEDALS,
    wire: [0x29, 0x00, 0x00, 0x03],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 40,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "dst-la-charger",
    kind: "dst",
    label: "La Charger",
    devices: BOTH_PEDALS,
    wire: [0x30, 0x00, 0x00, 0x03],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Tone",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "dst-darktale",
    kind: "dst",
    label: "Darktale",
    devices: BOTH_PEDALS,
    wire: [0x2b, 0x00, 0x00, 0x03],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Filter",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "dst-sora-fuzz",
    kind: "dst",
    label: "Sora Fuzz",
    devices: BOTH_PEDALS,
    wire: [0x22, 0x00, 0x00, 0x03],
    controls: [
      {
        index: 0,
        label: "Fuzz",
        min: 0,
        max: 100,
        step: 1,
        default: 40,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "dst-red-haze",
    kind: "dst",
    label: "Red Haze",
    devices: BOTH_PEDALS,
    wire: [0x24, 0x00, 0x00, 0x03],
    controls: [
      {
        index: 0,
        label: "Fuzz",
        min: 0,
        max: 100,
        step: 1,
        default: 40,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "dst-bass-od",
    kind: "dst",
    label: "Bass OD",
    devices: BOTH_PEDALS,
    wire: [0x40, 0x00, 0x00, 0x03],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Blend",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
];
