import { BOTH_PEDALS } from "@/device/catalog/shared";
import type { FxModel } from "@/device/catalog/types";

export const DST_MODELS: readonly FxModel[] = [
  {
    id: "dst-green-od",
    kind: "dst",
    label: "Green OD",
    description: "Based on legenary Ibanez® TS-808 Tube Screamer®* overdrive pedal. Since it was first shown to the world in 1979, TS808 has opened up a new world. There are countless guitarists who love it. It is a warm, delicate overdrive effect.Can be used as either an overdrive or a Boost, can be used in a variety of musical styles.",
    basedOn: "Ibanez® TS-808 Tube Screamer®",
    devices: BOTH_PEDALS,
    wire: [0x00, 0x00, 0x00, 0x03],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 40,
        display: "percent",
      },
      {
        index: 1,
        label: "Tone",
        min: 0,
        max: 100,
        step: 1,
        default: 70,
        display: "percent",
      },
      {
        index: 2,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "dst-yellow-od",
    kind: "dst",
    label: "Yellow OD",
    description: "Artist of the 70's was mostly using a fuzz distortion sound and the overdrive produced by it was not typical. It was however soon accepted as the new standard of guitar sound. It features an asymmetric circuit where the positive and negative halves of the waveform isn't distorted equally. The sound is therefore still close to the original even though distortion have been added.",
    devices: BOTH_PEDALS,
    wire: [0x02, 0x00, 0x00, 0x03],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 40,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "dst-super-od",
    kind: "dst",
    label: "Super OD",
    description: "The unique asymmetric overdrive effect circuit adds warm and pleasant overdrive effect to the traditional guitar timbre.",
    devices: BOTH_PEDALS,
    wire: [0x06, 0x00, 0x00, 0x03],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Tone",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "dst-sm-dist",
    kind: "dst",
    label: "SM Dist",
    description: "It is based on a classic orange three-knob distortion effector, which can be used to easily get the timbre characteristics of the 70s-80s.",
    basedOn: "classic orange three-knob distortion effector",
    devices: BOTH_PEDALS,
    wire: [0x2a, 0x00, 0x00, 0x03],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Tone",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "dst-plustortion",
    kind: "dst",
    label: "Plustortion",
    description: "This little yellow box has produced lots of great soundings in countless classic studio albums. Yeah, we're talking the legendary MXR® M104 Distortion +*, and this M104-based Plustortion. The Plustortion recreated the Germanium-powered soft clipping distortion, like what Randy Rhoads and other hard rockers do!",
    basedOn: "MXR® M104 Distortion +",
    devices: BOTH_PEDALS,
    wire: [0x29, 0x00, 0x00, 0x03],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 40,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "dst-la-charger",
    kind: "dst",
    label: "La Charger",
    description: "Based on MI Audio® Crunch Box®* distortion pedal. Sensitive and exquisite distortion beast, it satisfies all the passion of Riff and Solo.The response of each frequency band is balanced, the dynamic feedback is faithful to the fingertip, and the noise can be well controlled even at high gain.",
    basedOn: "MI Audio® Crunch Box®",
    devices: BOTH_PEDALS,
    wire: [0x30, 0x00, 0x00, 0x03],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Tone",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "dst-darktale",
    kind: "dst",
    label: "Darktale",
    description: "Based on legendary ProCo™ The Rat* distortion (early LM308 OP-amp version). The Rat* has come to life thanks to its wide range of Filter knob, bright and compact sound head, full end and strong plasticity, making it a favorite of many musicians.",
    basedOn: "ProCo™ The Rat distortion (early LM308 OP-amp version)",
    devices: BOTH_PEDALS,
    wire: [0x2b, 0x00, 0x00, 0x03],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Filter",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "dst-sora-fuzz",
    kind: "dst",
    label: "Sora Fuzz",
    description: "Based on legendary Dallas-Arbiter® Fuzz Face®* fuzz pedal. Dallas Arbiter conjured the sound of rock and roll for half a century in 1966 with a few simple transistors. The sound of Fuzz Face was heavy and sharp, and its sound influenced countless famous musicians.",
    basedOn: "Dallas-Arbiter® Fuzz Face®",
    devices: BOTH_PEDALS,
    wire: [0x22, 0x00, 0x00, 0x03],
    controls: [
      {
        index: 0,
        label: "Fuzz",
        min: 0,
        max: 100,
        step: 1,
        default: 40,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "dst-red-haze",
    kind: "dst",
    label: "Red Haze",
    description: "Based on legendary Dallas-Arbiter® Fuzz Face®* fuzz pedal. Dallas Arbiter conjured the sound of rock and roll for half a century in 1966 with a few simple transistors. The sound of Fuzz Face was heavy and sharp, and its sound influenced countless famous musicians.",
    basedOn: "Dallas-Arbiter® Fuzz Face®",
    devices: BOTH_PEDALS,
    wire: [0x24, 0x00, 0x00, 0x03],
    controls: [
      {
        index: 0,
        label: "Fuzz",
        min: 0,
        max: 100,
        step: 1,
        default: 40,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "dst-bass-od",
    kind: "dst",
    label: "Bass OD",
    description: "This is an overdrive effect device specially designed for bass. It combines the original bass sound with a unique overdrive effect to make a very good distortion effect while ensuring The original bass dynamic tone. It can also be used as a pretty good boost.",
    devices: BOTH_PEDALS,
    wire: [0x40, 0x00, 0x00, 0x03],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Blend",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
];
