import { BOTH_PEDALS } from "@/device/catalog/shared";
import type { FxModel } from "@/device/catalog/types";

export const EQ_MODELS: readonly FxModel[] = [
  {
    id: "eq-guitar-eq-1",
    kind: "eq",
    label: "Guitar EQ 1",
    devices: BOTH_PEDALS,
    wire: [0x35, 0x00, 0x00, 0x01],
    controls: [
      {
        index: 0,
        label: "125Hz",
        min: -50,
        max: 50,
        step: 1,
        default: 0,
        display: "bipolar",
      },
      {
        index: 1,
        label: "400Hz",
        min: -50,
        max: 50,
        step: 1,
        default: 0,
        display: "bipolar",
      },
      {
        index: 2,
        label: "800Hz",
        min: -50,
        max: 50,
        step: 1,
        default: 0,
        display: "bipolar",
      },
      {
        index: 3,
        label: "1.6kHz",
        min: -50,
        max: 50,
        step: 1,
        default: 0,
        display: "bipolar",
      },
      {
        index: 4,
        label: "4KHz",
        min: -50,
        max: 50,
        step: 1,
        default: 0,
        display: "bipolar",
      },
      {
        index: 5,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "eq-guitar-eq-2",
    kind: "eq",
    label: "Guitar EQ 2",
    devices: BOTH_PEDALS,
    wire: [0x36, 0x00, 0x00, 0x01],
    controls: [
      {
        index: 0,
        label: "100Hz",
        min: -50,
        max: 50,
        step: 1,
        default: 0,
        display: "bipolar",
      },
      {
        index: 1,
        label: "500Hz",
        min: -50,
        max: 50,
        step: 1,
        default: 0,
        display: "bipolar",
      },
      {
        index: 2,
        label: "1kHz",
        min: -50,
        max: 50,
        step: 1,
        default: 0,
        display: "bipolar",
      },
      {
        index: 3,
        label: "3kHz",
        min: -50,
        max: 50,
        step: 1,
        default: 0,
        display: "bipolar",
      },
      {
        index: 4,
        label: "6KHz",
        min: -50,
        max: 50,
        step: 1,
        default: 0,
        display: "bipolar",
      },
      {
        index: 5,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "eq-bass-eq-1",
    kind: "eq",
    label: "Bass EQ 1",
    devices: BOTH_PEDALS,
    wire: [0x39, 0x00, 0x00, 0x01],
    controls: [
      {
        index: 0,
        label: "33Hz",
        min: -50,
        max: 50,
        step: 1,
        default: 0,
        display: "bipolar",
      },
      {
        index: 1,
        label: "150Hz",
        min: -50,
        max: 50,
        step: 1,
        default: 0,
        display: "bipolar",
      },
      {
        index: 2,
        label: "600Hz",
        min: -50,
        max: 50,
        step: 1,
        default: 0,
        display: "bipolar",
      },
      {
        index: 3,
        label: "2kHz",
        min: -50,
        max: 50,
        step: 1,
        default: 0,
        display: "bipolar",
      },
      {
        index: 4,
        label: "8KHz",
        min: -50,
        max: 50,
        step: 1,
        default: 0,
        display: "bipolar",
      },
      {
        index: 5,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "eq-bass-eq-2",
    kind: "eq",
    label: "Bass EQ 2",
    devices: BOTH_PEDALS,
    wire: [0x3a, 0x00, 0x00, 0x01],
    controls: [
      {
        index: 0,
        label: "50Hz",
        min: -50,
        max: 50,
        step: 1,
        default: 0,
        display: "bipolar",
      },
      {
        index: 1,
        label: "120Hz",
        min: -50,
        max: 50,
        step: 1,
        default: 0,
        display: "bipolar",
      },
      {
        index: 2,
        label: "400Hz",
        min: -50,
        max: 50,
        step: 1,
        default: 0,
        display: "bipolar",
      },
      {
        index: 3,
        label: "800Hz",
        min: -50,
        max: 50,
        step: 1,
        default: 0,
        display: "bipolar",
      },
      {
        index: 4,
        label: "4.5KHz",
        min: -50,
        max: 50,
        step: 1,
        default: 0,
        display: "bipolar",
      },
      {
        index: 5,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "eq-mess-eq",
    kind: "eq",
    label: "Mess EQ",
    devices: BOTH_PEDALS,
    wire: [0x3c, 0x00, 0x00, 0x01],
    controls: [
      {
        index: 0,
        label: "80Hz",
        min: -50,
        max: 50,
        step: 1,
        default: 0,
        display: "bipolar",
      },
      {
        index: 1,
        label: "240Hz",
        min: -50,
        max: 50,
        step: 1,
        default: 0,
        display: "bipolar",
      },
      {
        index: 2,
        label: "750Hz",
        min: -50,
        max: 50,
        step: 1,
        default: 0,
        display: "bipolar",
      },
      {
        index: 3,
        label: "2.2kHz",
        min: -50,
        max: 50,
        step: 1,
        default: 0,
        display: "bipolar",
      },
      {
        index: 4,
        label: "6.6KHz",
        min: -50,
        max: 50,
        step: 1,
        default: 0,
        display: "bipolar",
      },
    ],
  },
];
