import { BOTH_PEDALS } from "@/device/catalog/shared";
import type { FxModel } from "@/device/catalog/types";

export const MOD_MODELS: readonly FxModel[] = [
  {
    id: "mod-a-chorus",
    kind: "mod",
    label: "A-Chorus",
    devices: BOTH_PEDALS,
    wire: [0x00, 0x00, 0x00, 0x04],
    controls: [
      {
        index: 0,
        label: "Depth",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Rate",
        min: 0.1,
        max: 10,
        step: 0.1,
        default: 0.5,
        display: "rate",
      },
      {
        index: 2,
        label: "Tone",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Sync",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "mod-b-chorus",
    kind: "mod",
    label: "B-Chorus",
    devices: BOTH_PEDALS,
    wire: [0x08, 0x00, 0x00, 0x04],
    controls: [
      {
        index: 0,
        label: "Depth",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Rate",
        min: 0.1,
        max: 10,
        step: 0.1,
        default: 0.5,
        display: "rate",
      },
      {
        index: 2,
        label: "Vol",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Sync",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "mod-jet",
    kind: "mod",
    label: "Jet",
    devices: BOTH_PEDALS,
    wire: [0x11, 0x00, 0x00, 0x04],
    controls: [
      {
        index: 0,
        label: "Depth",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Rate",
        min: 0.1,
        max: 10,
        step: 0.1,
        default: 0.5,
        display: "rate",
      },
      {
        index: 2,
        label: "P.Delay",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "F.Back",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Sync",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "mod-n-jet",
    kind: "mod",
    label: "N-Jet",
    devices: BOTH_PEDALS,
    wire: [0x13, 0x00, 0x00, 0x04],
    controls: [
      {
        index: 0,
        label: "Depth",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Rate",
        min: 0.1,
        max: 10,
        step: 0.1,
        default: 0.5,
        display: "rate",
      },
      {
        index: 2,
        label: "P.Delay",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "F.Back",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Sync",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "mod-o-phase",
    kind: "mod",
    label: "O-Phase",
    devices: BOTH_PEDALS,
    wire: [0x19, 0x00, 0x00, 0x04],
    controls: [
      {
        index: 0,
        label: "Rate",
        min: 0.1,
        max: 10,
        step: 0.1,
        default: 0.5,
        display: "rate",
      },
      {
        index: 1,
        label: "Sync",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "mod-m-vibe",
    kind: "mod",
    label: "M-Vibe",
    devices: BOTH_PEDALS,
    wire: [0x1f, 0x00, 0x00, 0x04],
    controls: [
      {
        index: 0,
        label: "Depth",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Rate",
        min: 0.1,
        max: 10,
        step: 0.1,
        default: 0.5,
        display: "rate",
      },
      {
        index: 2,
        label: "Sync",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "mod-v-roto",
    kind: "mod",
    label: "V-Roto",
    devices: BOTH_PEDALS,
    wire: [0x15, 0x00, 0x00, 0x04],
    controls: [
      {
        index: 0,
        label: "Depth",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Rate",
        min: 0.1,
        max: 10,
        step: 0.1,
        default: 0.5,
        display: "rate",
      },
      {
        index: 2,
        label: "Sync",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "mod-vibrato",
    kind: "mod",
    label: "Vibrato",
    devices: BOTH_PEDALS,
    wire: [0x17, 0x00, 0x00, 0x04],
    controls: [
      {
        index: 0,
        label: "Depth",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Rate",
        min: 0.1,
        max: 10,
        step: 0.1,
        default: 0.5,
        display: "rate",
      },
      {
        index: 2,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Sync",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "mod-o-trem",
    kind: "mod",
    label: "O-Trem",
    devices: BOTH_PEDALS,
    wire: [0x21, 0x00, 0x00, 0x04],
    controls: [
      {
        index: 0,
        label: "Depth",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Rate",
        min: 0.1,
        max: 10,
        step: 0.1,
        default: 0.5,
        display: "rate",
      },
      {
        index: 2,
        label: "Sync",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "mod-sine-trem",
    kind: "mod",
    label: "Sine Trem",
    devices: BOTH_PEDALS,
    wire: [0x26, 0x00, 0x00, 0x04],
    controls: [
      {
        index: 0,
        label: "Depth",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Rate",
        min: 0.1,
        max: 10,
        step: 0.1,
        default: 0.5,
        display: "rate",
      },
      {
        index: 2,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Sync",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "mod-bias-trem",
    kind: "mod",
    label: "Bias Trem",
    devices: BOTH_PEDALS,
    wire: [0x28, 0x00, 0x00, 0x04],
    controls: [
      {
        index: 0,
        label: "Depth",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Rate",
        min: 0.1,
        max: 10,
        step: 0.1,
        default: 0.5,
        display: "rate",
      },
      {
        index: 2,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Sync",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
      {
        index: 4,
        label: "Bias",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
];
