import { BOTH_PEDALS } from "@/device/catalog/shared";
import type { FxModel } from "@/device/catalog/types";

export const NS_MODELS: readonly FxModel[] = [
  {
    id: "ns-14-dst",
    kind: "ns",
    label: "14 DST",
    devices: BOTH_PEDALS,
    wire: [0x00, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-force-ocd",
    kind: "ns",
    label: "Force OCD",
    devices: BOTH_PEDALS,
    wire: [0x01, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-revolt-dst",
    kind: "ns",
    label: "Revolt DST",
    devices: BOTH_PEDALS,
    wire: [0x02, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-sweetdrive",
    kind: "ns",
    label: "SweetDrive",
    devices: BOTH_PEDALS,
    wire: [0x03, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-flagmandst",
    kind: "ns",
    label: "FlagmanDST",
    devices: BOTH_PEDALS,
    wire: [0x04, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-foxy-30",
    kind: "ns",
    label: "Foxy 30",
    devices: BOTH_PEDALS,
    wire: [0x05, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-twin-rvb",
    kind: "ns",
    label: "Twin RVB",
    devices: BOTH_PEDALS,
    wire: [0x06, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-match-30",
    kind: "ns",
    label: "Match 30",
    devices: BOTH_PEDALS,
    wire: [0x07, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-messstar-s",
    kind: "ns",
    label: "MessStar S",
    devices: BOTH_PEDALS,
    wire: [0x08, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-messjp-ch1",
    kind: "ns",
    label: "MessJP CH1",
    devices: BOTH_PEDALS,
    wire: [0x09, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-rock2-cl",
    kind: "ns",
    label: "Rock2 CL",
    devices: BOTH_PEDALS,
    wire: [0x0a, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-lany-lh20",
    kind: "ns",
    label: "Lany LH20",
    devices: BOTH_PEDALS,
    wire: [0x0b, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-supdual",
    kind: "ns",
    label: "SUPDual",
    devices: BOTH_PEDALS,
    wire: [0x0c, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-bj3-cl",
    kind: "ns",
    label: "BJ3 CL",
    devices: BOTH_PEDALS,
    wire: [0x0d, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-uk-bb-cl",
    kind: "ns",
    label: "UK BB CL",
    devices: BOTH_PEDALS,
    wire: [0x0e, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-bj3-od",
    kind: "ns",
    label: "BJ3 OD",
    devices: BOTH_PEDALS,
    wire: [0x0f, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-uk-bb-od",
    kind: "ns",
    label: "UK BB OD",
    devices: BOTH_PEDALS,
    wire: [0x10, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-uk-410-od",
    kind: "ns",
    label: "UK 410 OD",
    devices: BOTH_PEDALS,
    wire: [0x11, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-rock2-od",
    kind: "ns",
    label: "Rock2 OD",
    devices: BOTH_PEDALS,
    wire: [0x12, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-hw100",
    kind: "ns",
    label: "HW100",
    devices: BOTH_PEDALS,
    wire: [0x13, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-juice-cr-n",
    kind: "ns",
    label: "Juice CR N",
    devices: BOTH_PEDALS,
    wire: [0x14, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-foxy-30jmi",
    kind: "ns",
    label: "Foxy 30JMI",
    devices: BOTH_PEDALS,
    wire: [0x15, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-bog-dst",
    kind: "ns",
    label: "Bog DST",
    devices: BOTH_PEDALS,
    wire: [0x16, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-cv-xv",
    kind: "ns",
    label: "CV XV",
    devices: BOTH_PEDALS,
    wire: [0x17, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-messjp-ch2",
    kind: "ns",
    label: "MessJP CH2",
    devices: BOTH_PEDALS,
    wire: [0x18, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-messjp-ch3",
    kind: "ns",
    label: "MessJP CH3",
    devices: BOTH_PEDALS,
    wire: [0x19, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-uk-800",
    kind: "ns",
    label: "UK 800",
    devices: BOTH_PEDALS,
    wire: [0x1a, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-uk-slp",
    kind: "ns",
    label: "UK SLP",
    devices: BOTH_PEDALS,
    wire: [0x1b, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-uk410-dst1",
    kind: "ns",
    label: "UK410 DST1",
    devices: BOTH_PEDALS,
    wire: [0x1c, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-uk410-dst2",
    kind: "ns",
    label: "UK410 DST2",
    devices: BOTH_PEDALS,
    wire: [0x1d, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-uk-900",
    kind: "ns",
    label: "UK 900",
    devices: BOTH_PEDALS,
    wire: [0x1e, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-uk-2000",
    kind: "ns",
    label: "UK 2000",
    devices: BOTH_PEDALS,
    wire: [0x1f, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-uk-dsl",
    kind: "ns",
    label: "UK DSL",
    devices: BOTH_PEDALS,
    wire: [0x20, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-dizz-vh",
    kind: "ns",
    label: "Dizz VH",
    devices: BOTH_PEDALS,
    wire: [0x21, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-mess-triv",
    kind: "ns",
    label: "Mess TriV",
    devices: BOTH_PEDALS,
    wire: [0x22, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-mess-trim",
    kind: "ns",
    label: "Mess TriM",
    devices: BOTH_PEDALS,
    wire: [0x23, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-mess-2c",
    kind: "ns",
    label: "Mess 2C+",
    devices: BOTH_PEDALS,
    wire: [0x24, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-eagle-iron",
    kind: "ns",
    label: "Eagle Iron",
    devices: BOTH_PEDALS,
    wire: [0x25, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-handk-blk200",
    kind: "ns",
    label: "H&K BLK200",
    devices: BOTH_PEDALS,
    wire: [0x26, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-juicecrmax",
    kind: "ns",
    label: "JuiceCRMAX",
    devices: BOTH_PEDALS,
    wire: [0x27, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-agl-db-bs",
    kind: "ns",
    label: "AGL DB BS",
    devices: BOTH_PEDALS,
    wire: [0x28, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-ampg-6-bs",
    kind: "ns",
    label: "AMPG 6 BS",
    devices: BOTH_PEDALS,
    wire: [0x29, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-eb-faf-bs",
    kind: "ns",
    label: "EB Faf BS",
    devices: BOTH_PEDALS,
    wire: [0x2a, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-hack-bs",
    kind: "ns",
    label: "HACK BS",
    devices: BOTH_PEDALS,
    wire: [0x2b, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-pv-bs",
    kind: "ns",
    label: "PV BS",
    devices: BOTH_PEDALS,
    wire: [0x2c, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-matt-bs",
    kind: "ns",
    label: "MATT BS",
    devices: BOTH_PEDALS,
    wire: [0x2d, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-handk-bs",
    kind: "ns",
    label: "H&K BS",
    devices: BOTH_PEDALS,
    wire: [0x2e, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-juice-odbs",
    kind: "ns",
    label: "Juice ODBS",
    devices: BOTH_PEDALS,
    wire: [0x2f, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-ac-sim",
    kind: "ns",
    label: "AC SIM",
    devices: BOTH_PEDALS,
    wire: [0x30, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-piezo-sim",
    kind: "ns",
    label: "Piezo SIM",
    devices: BOTH_PEDALS,
    wire: [0x31, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-pccowboys",
    kind: "ns",
    label: "PCCowboys",
    devices: BOTH_PEDALS,
    wire: [0x32, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-pcranrg100",
    kind: "ns",
    label: "PCRanRG100",
    devices: BOTH_PEDALS,
    wire: [0x33, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-crategx65",
    kind: "ns",
    label: "_CrateGX65",
    devices: BOTH_PEDALS,
    wire: [0x34, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-mesaa2",
    kind: "ns",
    label: "_MesaA2",
    devices: BOTH_PEDALS,
    wire: [0x35, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-jmp-folkes",
    kind: "ns",
    label: "JMP FOLKES",
    devices: BOTH_PEDALS,
    wire: [0x36, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "ns-mesatrimod",
    kind: "ns",
    label: "MesaTriMod",
    devices: BOTH_PEDALS,
    wire: [0x37, 0x00, 0x00, 0x0f],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Middle",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
];
