import { BOTH_PEDALS, GP50_ONLY } from "@/device/catalog/shared";
import type { FxModel } from "@/device/catalog/types";

export const PRE_MODELS: readonly FxModel[] = [
  {
    id: "pre-comp",
    kind: "pre",
    label: "COMP",
    description: "Based on the legendary Ross™ Compressor. This is the originator of the guitar compression effect. It brings the guitar compression effect to the public and becomes an important element in the future. It has a very natural and mellow compression effect.",
    basedOn: "Based on Ross™ Compressor",
    devices: BOTH_PEDALS,
    wire: [0x00, 0x00, 0x00, 0x00],
    controls: [
      {
        index: 0,
        label: "Sustain",
        min: 0,
        max: 100,
        step: 1,
        default: 20,
        display: "percent",
      },
      {
        index: 1,
        label: "Vol",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "pre-comp4",
    kind: "pre",
    label: "COMP4",
    description: "Based on the Keeley® C4 4-knob compressor*. A recording studio - level compression effect. Clear sense of hierarchy, the right amount of high frequency makes your guitar sound brighter.",
    basedOn: "Based on Keeley® C4 4-knob compressor",
    devices: BOTH_PEDALS,
    wire: [0x01, 0x00, 0x00, 0x00],
    controls: [
      {
        index: 0,
        label: "Sustain",
        min: 0,
        max: 100,
        step: 1,
        default: 20,
        display: "percent",
      },
      {
        index: 1,
        label: "Attack",
        min: 0,
        max: 100,
        step: 1,
        default: 60,
        display: "percent",
      },
      {
        index: 2,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Clip",
        min: 0,
        max: 100,
        step: 1,
        default: 10,
        display: "percent",
      },
    ],
  },
  {
    id: "pre-boost",
    kind: "pre",
    label: "Boost",
    description: "Based on famous Xotic® EP Booster* pedal. Provides +20DB of pure stimulation lift, strong low frequency, bright high frequency, making clear sound more pleasant.",
    basedOn: "Based on Xotic® EP Booster*",
    devices: BOTH_PEDALS,
    wire: [0x1a, 0x00, 0x00, 0x00],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 20,
        display: "percent",
      },
      {
        index: 1,
        label: "+3DB",
        min: 0,
        max: 1,
        step: 1,
        default: 1,
        display: "toggle",
      },
      {
        index: 2,
        label: "Bright",
        min: 0,
        max: 1,
        step: 1,
        default: 1,
        display: "toggle",
      },
    ],
  },
  {
    id: "pre-micro-boost",
    kind: "pre",
    label: "Micro Boost",
    description: "Based on the legendary MXR® M133 Micro Amp2 pedal. Providing up to 20dB of gain, the Micro Boost elevates your amp sound without changing its tonal character.",
    basedOn: "Based on MXR® M133 Micro Amp2 pedal",
    devices: BOTH_PEDALS,
    wire: [0x14, 0x00, 0x00, 0x00],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "pre-b-boost",
    kind: "pre",
    label: "B-Boost",
    description: "Any guitarist can benefit from the Xotic® BB Preamp* overdrive pedal. The pedal works equally well for getting thick and creamy overdrive tones with great sustain as it does for pushing the clean front end of an already driven amp with up to 30dB of boost.",
    basedOn: "Based on Xotic® BB Preamp",
    devices: BOTH_PEDALS,
    wire: [0x0b, 0x00, 0x00, 0x00],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 20,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "pre-toucher",
    kind: "pre",
    label: "Toucher",
    description: "Control the wah sound by playing intensity. A wide range d envelope filter (a.k.a. touch wah) designed for guitarists and bassists that is touch-sensitive and flexible.",
    devices: BOTH_PEDALS,
    wire: [0x0f, 0x00, 0x00, 0x01],
    controls: [
      {
        index: 0,
        label: "Sense",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Range",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Q",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Mix",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Mode (Guitar/Bass)",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "pre-crier",
    kind: "pre",
    label: "Crier",
    description: "Set the rate to make the wah pedal work regularly. Providing a variable auto wah effect for both guitars and basses.",
    devices: BOTH_PEDALS,
    wire: [0x15, 0x00, 0x00, 0x01],
    controls: [
      {
        index: 0,
        label: "Depth",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Rate",
        min: 0.1,
        max: 10,
        step: 0.1,
        default: 0.5,
        display: "rate",
      },
      {
        index: 2,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Low",
        min: 0,
        max: 100,
        step: 1,
        default: 25,
        display: "percent",
      },
      {
        index: 4,
        label: "Q",
        min: 0,
        max: 100,
        step: 1,
        default: 70,
        display: "percent",
      },
      {
        index: 5,
        label: "High",
        min: 0,
        max: 100,
        step: 1,
        default: 60,
        display: "percent",
      },
      {
        index: 6,
        label: "Sync",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
        devices: GP50_ONLY,
      },
    ],
  },
  {
    id: "pre-c-wah",
    kind: "pre",
    label: "C-Wah",
    description: "Based on legendary Dunlop® CryBaby®* wah pedal. ",
    basedOn: "Based on Dunlop® CryBaby®",
    devices: GP50_ONLY,
    wire: [0x08, 0x00, 0x00, 0x05],
    controls: [
      {
        index: 0,
        label: "Range",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Q",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Volume",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Position",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "pre-octa",
    kind: "pre",
    label: "OCTA",
    description: "Provides polyphonic octave effect.",
    devices: BOTH_PEDALS,
    wire: [0x21, 0x00, 0x00, 0x01],
    controls: [
      {
        index: 0,
        label: "Low",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "High",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Dry",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "pre-pitch",
    kind: "pre",
    label: "Pitch",
    description: "Polyphonic pitch shifter/harmonizer. High/Low: Controls the high/low pitch shifting range by semitones",
    devices: BOTH_PEDALS,
    wire: [0x23, 0x00, 0x00, 0x01],
    controls: [
      {
        index: 0,
        label: "High",
        min: 0,
        max: 24,
        step: 1,
        default: 12,
        display: "enum",
      },
      {
        index: 1,
        label: "Low",
        min: -24,
        max: 0,
        step: 1,
        default: -12,
        display: "bipolar",
      },
      {
        index: 2,
        label: "Dry",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "H-Vol",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "L-VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "pre-detune",
    kind: "pre",
    label: "Detune",
    description: "This is a detuning effect that combines a slightly shifted signal with the original signal to create a chorus-like tone.",
    devices: BOTH_PEDALS,
    wire: [0x29, 0x00, 0x00, 0x01],
    controls: [
      {
        index: 0,
        label: "Detune",
        min: -50,
        max: 50,
        step: 1,
        default: -25,
        display: "bipolar",
      },
      {
        index: 1,
        label: "Wet",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Dry",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "pre-ac-sim",
    kind: "pre",
    label: "AC Sim",
    description: "An acoustic guitar simulator effect",
    devices: GP50_ONLY,
    wire: [0x01, 0x00, 0x00, 0x01],
    controls: [
      {
        index: 0,
        label: "Body",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Top",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Volume",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Mode",
        min: 0,
        max: 3,
        step: 1,
        default: 0,
        display: "enum",
      },
    ],
  },
];
