import { BOTH_PEDALS } from "@/device/catalog/shared";
import type { FxModel } from "@/device/catalog/types";

export const PRE_MODELS: readonly FxModel[] = [
  {
    id: "pre-comp",
    kind: "pre",
    label: "COMP",
    devices: BOTH_PEDALS,
    wire: [0x00, 0x00, 0x00, 0x00],
    controls: [
      {
        index: 0,
        label: "Sustain",
        min: 0,
        max: 100,
        step: 1,
        default: 20,
        display: "percent",
      },
      {
        index: 1,
        label: "Vol",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "pre-comp4",
    kind: "pre",
    label: "COMP4",
    devices: BOTH_PEDALS,
    wire: [0x01, 0x00, 0x00, 0x00],
    controls: [
      {
        index: 0,
        label: "Sustain",
        min: 0,
        max: 100,
        step: 1,
        default: 20,
        display: "percent",
      },
      {
        index: 1,
        label: "Attack",
        min: 0,
        max: 100,
        step: 1,
        default: 60,
        display: "percent",
      },
      {
        index: 2,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Clip",
        min: 0,
        max: 100,
        step: 1,
        default: 10,
        display: "percent",
      },
    ],
  },
  {
    id: "pre-boost",
    kind: "pre",
    label: "Boost",
    devices: BOTH_PEDALS,
    wire: [0x1a, 0x00, 0x00, 0x00],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 20,
        display: "percent",
      },
      {
        index: 1,
        label: "+3DB",
        min: 0,
        max: 1,
        step: 1,
        default: 1,
        display: "toggle",
      },
      {
        index: 2,
        label: "Bright",
        min: 0,
        max: 1,
        step: 1,
        default: 1,
        display: "toggle",
      },
    ],
  },
  {
    id: "pre-micro-boost",
    kind: "pre",
    label: "Micro Boost",
    devices: BOTH_PEDALS,
    wire: [0x14, 0x00, 0x00, 0x00],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "pre-b-boost",
    kind: "pre",
    label: "B-Boost",
    devices: BOTH_PEDALS,
    wire: [0x0b, 0x00, 0x00, 0x00],
    controls: [
      {
        index: 0,
        label: "Gain",
        min: 0,
        max: 100,
        step: 1,
        default: 20,
        display: "percent",
      },
      {
        index: 1,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Bass",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Treble",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "pre-toucher",
    kind: "pre",
    label: "Toucher",
    devices: BOTH_PEDALS,
    wire: [0x0f, 0x00, 0x00, 0x01],
    controls: [
      {
        index: 0,
        label: "Sense",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Range",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Q",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Mix",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Mode (Guitar/Bass)",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "pre-crier",
    kind: "pre",
    label: "Crier",
    devices: BOTH_PEDALS,
    wire: [0x15, 0x00, 0x00, 0x01],
    controls: [
      {
        index: 0,
        label: "Depth",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Rate",
        min: 0.1,
        max: 10,
        step: 0.1,
        default: 0.5,
        display: "rate",
      },
      {
        index: 2,
        label: "VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Low",
        min: 0,
        max: 100,
        step: 1,
        default: 25,
        display: "percent",
      },
      {
        index: 4,
        label: "Q",
        min: 0,
        max: 100,
        step: 1,
        default: 70,
        display: "percent",
      },
      {
        index: 5,
        label: "High",
        min: 0,
        max: 100,
        step: 1,
        default: 60,
        display: "percent",
      },
      {
        index: 6,
        label: "Sync",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "pre-c-wah",
    kind: "pre",
    label: "C-Wah",
    devices: BOTH_PEDALS,
    wire: [0x08, 0x00, 0x00, 0x05],
    controls: [
      {
        index: 0,
        label: "Range",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Q",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Volume",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Position",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "pre-octa",
    kind: "pre",
    label: "OCTA",
    devices: BOTH_PEDALS,
    wire: [0x21, 0x00, 0x00, 0x01],
    controls: [
      {
        index: 0,
        label: "Low",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "High",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Dry",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "pre-pitch",
    kind: "pre",
    label: "Pitch",
    devices: BOTH_PEDALS,
    wire: [0x23, 0x00, 0x00, 0x01],
    controls: [
      {
        index: 0,
        label: "High",
        min: 0,
        max: 24,
        step: 1,
        default: 12,
        display: "enum",
      },
      {
        index: 1,
        label: "Low",
        min: -24,
        max: 0,
        step: 1,
        default: -12,
        display: "bipolar",
      },
      {
        index: 2,
        label: "Dry",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "H-Vol",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "L-VOL",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "pre-detune",
    kind: "pre",
    label: "Detune",
    devices: BOTH_PEDALS,
    wire: [0x29, 0x00, 0x00, 0x01],
    controls: [
      {
        index: 0,
        label: "Detune",
        min: -50,
        max: 50,
        step: 1,
        default: -25,
        display: "bipolar",
      },
      {
        index: 1,
        label: "Wet",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Dry",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
    ],
  },
  {
    id: "pre-ac-sim",
    kind: "pre",
    label: "AC Sim",
    devices: BOTH_PEDALS,
    wire: [0x01, 0x00, 0x00, 0x01],
    controls: [
      {
        index: 0,
        label: "Body",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 1,
        label: "Top",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Volume",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Mode",
        min: 0,
        max: 3,
        step: 1,
        default: 0,
        display: "enum",
      },
    ],
  },
];
