import { BOTH_PEDALS } from "@/device/catalog/shared";
import type { FxModel } from "@/device/catalog/types";

export const RVB_MODELS: readonly FxModel[] = [
  {
    id: "rvb-air",
    kind: "rvb",
    label: "Air",
    description: "An airy reverb effect with natural decays.",
    devices: BOTH_PEDALS,
    wire: [0x0b, 0x00, 0x00, 0x0c],
    controls: [
      {
        index: 0,
        label: "Mix",
        min: 0,
        max: 100,
        step: 1,
        default: 30,
        display: "percent",
      },
      {
        index: 2,
        label: "Decay",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Damp",
        min: 0,
        max: 100,
        step: 1,
        default: 0,
        display: "percent",
      },
      {
        index: 6,
        label: "Trail",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "rvb-room",
    kind: "rvb",
    label: "Room",
    description: "Simulates the spaciousness of a room.",
    devices: BOTH_PEDALS,
    wire: [0x00, 0x00, 0x00, 0x0c],
    controls: [
      {
        index: 0,
        label: "Mix",
        min: 0,
        max: 100,
        step: 1,
        default: 30,
        display: "percent",
      },
      {
        index: 2,
        label: "Decay",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Trail",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "rvb-hall",
    kind: "rvb",
    label: "Hall",
    description: "Simulates the spaciousness of a performance hall.",
    devices: BOTH_PEDALS,
    wire: [0x01, 0x00, 0x00, 0x0c],
    controls: [
      {
        index: 0,
        label: "Mix",
        min: 0,
        max: 100,
        step: 1,
        default: 30,
        display: "percent",
      },
      {
        index: 2,
        label: "Decay",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Trail",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "rvb-church",
    kind: "rvb",
    label: "Church",
    description: "Simulates the spaciousness of a church.",
    devices: BOTH_PEDALS,
    wire: [0x02, 0x00, 0x00, 0x0c],
    controls: [
      {
        index: 0,
        label: "Mix",
        min: 0,
        max: 100,
        step: 1,
        default: 30,
        display: "percent",
      },
      {
        index: 2,
        label: "Decay",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Trail",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "rvb-plate-l",
    kind: "rvb",
    label: "Plate L",
    description: "Simulates the sound character produced by a large plate reverberator.",
    devices: BOTH_PEDALS,
    wire: [0x10, 0x00, 0x00, 0x0c],
    controls: [
      {
        index: 0,
        label: "Mix",
        min: 0,
        max: 100,
        step: 1,
        default: 30,
        display: "percent",
      },
      {
        index: 2,
        label: "Decay",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 6,
        label: "Trail",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "rvb-plate",
    kind: "rvb",
    label: "Plate",
    description: "Simulates the sound character produced by a vintage small plate reverberator.",
    devices: BOTH_PEDALS,
    wire: [0x0f, 0x00, 0x00, 0x0c],
    controls: [
      {
        index: 0,
        label: "Mix",
        min: 0,
        max: 100,
        step: 1,
        default: 30,
        display: "percent",
      },
      {
        index: 2,
        label: "Decay",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Damp",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 6,
        label: "Trail",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "rvb-spring",
    kind: "rvb",
    label: "Spring",
    description: "Simulates the sound character produced by a vintage spring reverberator.",
    devices: BOTH_PEDALS,
    wire: [0x04, 0x00, 0x00, 0x0c],
    controls: [
      {
        index: 0,
        label: "Mix",
        min: 0,
        max: 100,
        step: 1,
        default: 30,
        display: "percent",
      },
      {
        index: 1,
        label: "Decay",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 3,
        label: "Trail",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "rvb-n-star",
    kind: "rvb",
    label: "N-Star",
    description: "Special-tuned reverb effect with lush, bright decays.",
    devices: BOTH_PEDALS,
    wire: [0x06, 0x00, 0x00, 0x0c],
    controls: [
      {
        index: 0,
        label: "Mix",
        min: 0,
        max: 100,
        step: 1,
        default: 30,
        display: "percent",
      },
      {
        index: 1,
        label: "Decay",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Trail",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "rvb-deepsea",
    kind: "rvb",
    label: "Deepsea",
    description: "Special-tuned reverb effect with huge, deep decays.",
    devices: BOTH_PEDALS,
    wire: [0x07, 0x00, 0x00, 0x0c],
    controls: [
      {
        index: 0,
        label: "Mix",
        min: 0,
        max: 100,
        step: 1,
        default: 30,
        display: "percent",
      },
      {
        index: 1,
        label: "Decay",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 2,
        label: "Trail",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
  {
    id: "rvb-sweet-space",
    kind: "rvb",
    label: "Sweet Space",
    description: "Produces a modulated reverb effect that is lush and sweet.",
    devices: BOTH_PEDALS,
    wire: [0x15, 0x00, 0x00, 0x0c],
    controls: [
      {
        index: 0,
        label: "Mix",
        min: 0,
        max: 100,
        step: 1,
        default: 30,
        display: "percent",
      },
      {
        index: 2,
        label: "Decay",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 4,
        label: "Damp",
        min: 0,
        max: 100,
        step: 1,
        default: 0,
        display: "percent",
      },
      {
        index: 5,
        label: "Mod",
        min: 0,
        max: 100,
        step: 1,
        default: 50,
        display: "percent",
      },
      {
        index: 6,
        label: "Trail",
        min: 0,
        max: 1,
        step: 1,
        default: 0,
        display: "toggle",
      },
    ],
  },
];
